# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:

  metas:
    title:        inzercia.utociste.sk
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [jquery-1.4.4.min.js, main.js]

  has_layout:     true
  layout:         layout
